apiVersion: v1
kind: Pod
metadata:
  name: kafkaconsumer
  namespace: kafka
spec:
  containers:
  - name: kafkaconsumer
    image: 372456142993.dkr.ecr.eu-west-1.amazonaws.com/pearlai/kafkaconsumer:latest
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    - name: KAFKA_BOOTSTRAP
      value: "bootstrap.kafka:9092"
    - name: KAFKA_SCHEMA_REGISTRY_URL
      value: "http://avro-schemas:80"
    - name: KAFKA_TOPIC
      value: "test-raw-messages"
    - name: KAFKA_CONSUMER_GROUP_ID
      value: "test-db-topics"
    - name: KAFKA_CONSUMER_OFFSET_RESET
      value: "earliest"
    imagePullPolicy: Always
  restartPolicy: Never