apiVersion: v1
kind: Pod
metadata:
  name: kafka-t-pc
  namespace: kafka
spec:
  containers:
  - name: kafka-test-pc
    image: 372456142993.dkr.ecr.eu-west-1.amazonaws.com/pearlai/kafkatestproducer:latest
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    - name: AVRO_KEY
      value: "true"
    - name: KAFKA_BOOTSTRAP
      value: "bootstrap.kafka:9092"
    - name: KAFKA_SCHEMA_REGISTRY_URL
      value: "http://avro-schemas:80"
    - name: KAFKA_PRODUCER_TOPIC
      value: "test-raw-messages"
    - name: KAFKA_CONSUMER_TOPIC
      value: "test-max-rssi"
    - name: KAFKA_CONSUMER_GROUP_ID
      value: "test-db-topics"
    - name: KAFKA_CONSUMER_OFFSET_RESET
      value: "earliest"
    imagePullPolicy: Always
  restartPolicy: Never