apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: kafka
spec:
  containers:
  - name: ubuntu
    image: pstauffer/curl:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always